apiVersion: apps/v1
kind: Deployment
metadata:
  name: golinks
  labels:
    app: golinks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golinks
  template:
    metadata:
      labels:
        app: golinks
    spec:
      containers:
        - name: web
          image: golinks-web:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "development"
            - name: API_URL
              value: "http://localhost:8080"
        - name: api
          image: golinks-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "development"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: golinks-secrets
                  key: database-url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: golinks-secrets
                  key: jwt-secret
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: golinks-secrets
                  key: google-client-id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: golinks-secrets
                  key: google-client-secret
